package appConfig

const (
	DROPCASES_PORT             = "PORT"
	DROPCASES_API_TOKEN_FILE   = "DROPCASES_API_TOKEN_FILE"
	DROPCASES_API_TOKEN_MEMBER = "DROPCASES_API_TOKEN_MEMBER"
	DROPCASES_ADMIN_MEMBER_ID  = "DROPCASES_ADMIN_MEMBER_ID"
)
